### ISSUE TITLE
Update Hugo to 0.18.1

### ISSUE THREAD

**Issue by jamzi** [garazaFRI/garaza-webpage#10]
We should update docker image to the latest version of Hugo (0.18.1). I am using it locally and it works ok with FRI Garaža webpage.

Changelog for 0.18 show that is faster and more efficient to 0.17.
"Hugo again continues its trend of each release being faster than the last. It’s quite a challenge to consistently add significant new functionality and simultaneously dramatically improve performance. Running this benchmark with these sites (renders to memory) shows about 60% reduction in time spent and 30% reduction in memory usage compared to Hugo 0.17."

**Comment by matjazp** [comment]
Done. (matjazp/hugo-ci updated to 0.18.1)
