### ISSUE TITLE
Fix Events for mobile devices

### ISSUE THREAD

**Issue by matjazp** [garazaFRI/garaza-webpage#13]
when viewing Events on a mobile device http://garaza.io/event/, there is some overlap of text and a date.

**Comment by jamzi** [comment]
Fixed in #14

**Comment by matjazp** [comment]
Ugh.. didn't check how this renders in the desktop browser before I merged #14 - now the date is too far left on the Desktop.
Can you also fix some added extra spacing between date and year on the mobile devices?

**Comment by jamzi** [comment]
Fixes in #15
