### ISSUE TITLE
Garaža odpira svoja vrata does not display on homepage

### ISSUE THREAD

**Issue by jamzi** [garazaFRI/garaza-webpage#7]
This is caused by the limit of posts for pagination (number of events with the Salesforce event went over 10). I will prepare a fix for that and submit a pull request.

**Comment by jamzi** [comment]
Pull request #8

**Comment by matjazp** [comment]
Right now we don't write posts, so maybe it is better if we just delete this? This opening post is getting pretty old.

**Comment by jamzi** [comment]
Ok. Should we at least include some link on homepage where it says: "Želiš uresničiti svoje ideje? Postani del Garaže." to the "Pridruži se" view. If I am not wrong it should be a call to action, but now it looks a little bit odd, just sayin...

**Comment by matjazp** [comment]
ok

**Comment by jamzi** [comment]
Resolved in the #8
